sudo: required
dist: trusty
language: cpp
os:
- linux
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
script:
- "./package.sh"
before_deploy:
- export RELEASE_FILE=bin.tar.gz
- ls
- echo "Deploying $RELEASE_FILE to GitHub"
deploy:
  provider: releases
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    repo: Malfoy/BCOOL
    overwrite: true
  api-key:
    secure: GC3NUnHXxBW3Jf+1xJ8I2P4qOObi6QkBq8zP+Jvqcd/NH6tfExHprenf3P6q0+t8MGrv3TKC6AtM2rUw/KcsgcAdKL0UgwEi9dUg3jVA3X2aPNMIfyeRsxZTvuSwvF0Fys38TVyZ2fWy1brd8j0q0aFUMNzYYrwaRW3beHvHcMVjEogIYFsYb/BKHpFPN51I7rZn044deRZRzNjCT0JXeFDntiptQ7KXD40n+QF88JXoHRTymEWM7QFp2Pg5hN8dCacYCUtFkBQQmHQ26IBwKsx0DlKd9OiVOjDXURYUhWCOCN3jNAiV6kvrQY2d5+n+NcljMUvbbDUjKYaNZsnoDlYbc2hHsrvjK1uJZQQ7okefEp4MP5H++BhH0KivLk0n0JMwPq3ftCYcMOlsJi6PHd5Vw2nF34PPe4ZgbGlcYFZK79r3mpmgMgu9wCVUdKQddafS0JviBwvfhvR1B+8zbfq6hL+gsi+0CtJesNEuQQ3R6+1FJ2zgeVj45tbsljYR/0RxVIex/cN3MFPfCJRc1f+PYS8fxIj20lEqAvQUHxzlBSAADTSjFTfVGRzl9SWSCwo2ToKrsurFaMa+fmhcFDQsMzA4+CcRRdIXQBiDZojy6DZszKnkAMUSn9/vLHAHhrqxSL3EYc1ROfLjIK1KxGiwblfZ4k8ikCF4SEGXxAY=
